version: '3.8'

services:
  elasticsearch:
    build:
      context: ./elasticsearchDock
      dockerfile: Dockerfile
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=ELASTIC_PASSWORD
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data

  grpcserver:
    build:
      context: ./data_ingest_worker
      dockerfile: Dockerfile
    container_name: grpcserver
    ports:
      - "4001:4001"

  httpserver:
    build:
      context: ./data_store_service
      dockerfile: Dockerfile
    container_name: httpserver
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
      - grpcserver

volumes:
  esdata:
    driver: local
